spring:
  profiles: dev

  datasource:
    url: jdbc:h2:mem:sdw2023
    driver-class-name: org.h2.Driver
    username: guize
    password:

  jpa:
    properties:
      hibernate:
        ddl-auto: update
        jdbc:
          lob:
            non_contextual_creation: true
      show-sql: true

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false

  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

h2:
  console:
    enabled: true
    path: /h2-console
    settings:
      trace: false
      web-allow-others: false

logging:
  level:
    org:
      springframework:
        boot: DEBUG
